on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: app-prod-alexvnilsson-edu-01
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '12.x'
  IMAGE_NAME: alexvnilsson-edu-landing
  IMAGE_VERSION: latest

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Build image
      run: |
        bin/docker-build
    - name: Login to ACR
      id: ecr
      uses: elgohr/acr-login-action@master
      with:
        service_principal: ${{ secrets.ACR_PRINCIPAL }}
        service_principal_password: ${{ secrets.ACR_PRINCIPAL_PASSWORD }}
        tenant: ${{ secrets.TENANT }}
        registry: ${{ secrets.REGISTRY }}
        repository: ${{ secrets.REPOSITORY }}
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: myDocker/repository
        username: ${{ steps.ecr.outputs.username }}
        password: ${{ steps.ecr.outputs.password }}
        registry: ${{ secrets.REGISTRY }}
