on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_PACKAGE_PATH: "."
  AZURE_WEBAPP_URL: edu.alexvnilsson.se
  DOCKER_NAMESPACE: alexvnilssonedu
  DOCKER_REPOSITORY: landing
  NODE_VERSION: "12.x"

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPOSITORY }}
        tag_with_ref: true
