on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 12.x
  GITHUB_PAGES_DIRECTORY: public
  GITHUB_PAGES_BRANCH: master

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - run: |
          npx gatsby build
          npx gh-pages --dest {{ env.GITHUB_PAGES_DIRECTORY }} --branch {{ env.GITHUB_PAGES_BRANCH }}
