on:
  push:
    branches:
      - master

env:
  AZURE_CR_DOMAIN: alexvnilsson.azurecr.io
  AZURE_WEBAPP_PACKAGE_PATH: "."
  AZURE_WEBAPP_URL: edu.alexvnilsson.se
  IMAGE_NAME: alexvnilsson-edu-landing
  NODE_VERSION: "12.x"

jobs:
  build:
    name: Build image
    runs-on: [self-hosted, linux]
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CR_DOMAIN }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: echo "::set-env name=IMAGE_TAG::$(git rev-parse --short HEAD)"
    - name: Build image ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      run: |
        build-tools/docker/build ${{ env.IMAGE_NAME }} -t latest -t ${{ env.IMAGE_TAG }}
    - name: Publish image ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      run: |
        build-tools/docker-tool tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_TAG }} --registry ${{ env.AZURE_CR_DOMAIN }}
        build-tools/docker-tool publish ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --registry ${{ env.AZURE_CR_DOMAIN }}
    # - name: "Deploy to container registry"
    #   uses: "azure/aci-deploy@v1"
    #   with:
    #     image: ${{ env.AZURE_CR_DOMAIN }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
    #     registry-username: ${{ secrets.REGISTRY_USERNAME }}
    #     registry-password: ${{ secrets.REGISTRY_PASSWORD }}
    #     resource-group: rg-prod-alexvnilsson-01
    #     location: "north europe"
    #     name: ${{ env.IMAGE_NAME }}-container
    #     dns-name-label: ${{ env.AZURE_WEBAPP_URL }}
